export const policeDivisions = [
    "Colombo Central Police Division",
    "Colombo North Police Division",
    "Colombo South Police Division",
    "Nugegoda Police Division",
    "Mount Lavinia Police Division",
    "Kelaniya Police Division",
    "Gampaha Police Division",
    "Negombo Police Division",
    "Panadura Police Division",
    "Kalutara Police Division",
    "Kandy Police Division",
    "Gampola Police Division",
    "Theldeniya Police Division",
    "Matale Police Division",
    "Nuwaraeliya Police Division",
    "Hatton Police Division",
];
export const policeStations = [
    "Pettah",
    "Keselwatta",
    "Dam Street",
    "Wolfendhal Street",
    "Fort",
    "Slave Island",
    "Maradana",
    "Maligawatta"
];

export const offences = [
    "Driving without a valid license",
    "Driving under the influence of alcohol",
    "Driving without a valid insurance",
    "Driving without a valid registration",
    "Driving without a valid emission test",
    "Driving without a valid revenue license",
    "Driving without a valid route permit",
    "Driving without a valid fitness certificate",
    "Driving without a valid number plate",
    "Driving without a valid speed limiter",
    "Driving without a valid speedometer",
    "Driving without a valid side mirror",
    "Driving without a valid rear mirror",
    "Driving without a valid headlight",
    "Driving without a valid tail light",
    "Driving without a valid indicator",
    "Driving without a valid horn",
    "Driving without a valid wiper",
    "Driving without a valid seat belt",
    "Driving without a valid helmet",
    "Driving without a valid reflector",
    "Driving without a valid mudguard",
    "Driving without a valid silencer",
    "Driving without a valid foot rest",
    "Driving without a valid handle bar",
    "Driving without a valid stand",
    "Driving without a valid chain cover",
    "Driving without a valid number plate light",
    "Driving without a valid number plate sticker",
    "Driving without a valid number plate reflector",
    "Driving without a valid number plate screw",
    "Driving without a valid number plate lock",
    "Driving without a valid number plate frame",
    "Driving without a valid number plate cover",
    "Driving without a valid number plate holder",
    "Driving without a valid number plate bolt",
    "Driving without a valid number plate nut",
    "Driving without a valid number plate washer",
    "Driving without a valid number plate clamp",
    "Driving without a valid number plate bracket",
]

export const provinces = [
    "Western Province",
    "Central Province",
    "Southern Province",
    "Northern Province",
    "Eastern Province",
    "North Western Province",
    "North Central Province",
    "Uva Province",
]